
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analyzers;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int menorque = 45;
  public static final int ancho = 29;
  public static final int menor = 43;
  public static final int textob = 21;
  public static final int ddq = 6;
  public static final int textoa = 20;
  public static final int opar = 54;
  public static final int identificador = 60;
  public static final int cllv = 53;
  public static final int salto = 13;
  public static final int echo = 62;
  public static final int beginHS = 69;
  public static final int getpath = 68;
  public static final int hypen = 39;
  public static final int borde = 32;
  public static final int compi = 8;
  public static final int setcontenido = 66;
  public static final int setalto = 78;
  public static final int imagen = 19;
  public static final int rgb = 7;
  public static final int boton = 22;
  public static final int div = 5;
  public static final int getancho = 76;
  public static final int clickboton = 75;
  public static final int cadena = 61;
  public static final int dot = 41;
  public static final int insertar = 74;
  public static final int semicolon = 35;
  public static final int crearparrafo = 14;
  public static final int else_ = 64;
  public static final int getcontenido = 27;
  public static final int getalto = 81;
  public static final int asterisk = 40;
  public static final int dolar = 36;
  public static final int fila = 16;
  public static final int igualque = 48;
  public static final int columnac = 17;
  public static final int settexto = 85;
  public static final int ollv = 52;
  public static final int ocorch = 57;
  public static final int or = 50;
  public static final int mayorque = 46;
  public static final int paragraph = 3;
  public static final int fondo = 24;
  public static final int open = 2;
  public static final int id = 30;
  public static final int alineacion = 25;
  public static final int parrafo = 12;
  public static final int ccorch = 58;
  public static final int close = 4;
  public static final int path = 26;
  public static final int true_ = 33;
  public static final int columna = 18;
  public static final int tabla = 15;
  public static final int titulo = 10;
  public static final int and = 49;
  public static final int endHS = 79;
  public static final int mayor = 44;
  public static final int espacio = 23;
  public static final int cabecera = 9;
  public static final int texto = 31;
  public static final int crearboton = 84;
  public static final int creartextob = 72;
  public static final int comma = 59;
  public static final int creartextoa = 71;
  public static final int EOF = 0;
  public static final int if_ = 63;
  public static final int repetir = 65;
  public static final int hashtag = 56;
  public static final int cuerpo = 11;
  public static final int numero = 42;
  public static final int cpar = 55;
  public static final int alto = 28;
  public static final int crearimagen = 73;
  public static final int error = 1;
  public static final int setancho = 80;
  public static final int diferente = 47;
  public static final int gettexto = 86;
  public static final int setborde = 83;
  public static final int not = 51;
  public static final int setpath = 77;
  public static final int equal = 37;
  public static final int false_ = 34;
  public static final int plus = 38;
  public static final int creartabla = 82;
  public static final int getalineacion = 70;
  public static final int setalineacion = 67;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "open",
  "paragraph",
  "close",
  "div",
  "ddq",
  "rgb",
  "compi",
  "cabecera",
  "titulo",
  "cuerpo",
  "parrafo",
  "salto",
  "crearparrafo",
  "tabla",
  "fila",
  "columnac",
  "columna",
  "imagen",
  "textoa",
  "textob",
  "boton",
  "espacio",
  "fondo",
  "alineacion",
  "path",
  "getcontenido",
  "alto",
  "ancho",
  "id",
  "texto",
  "borde",
  "true_",
  "false_",
  "semicolon",
  "dolar",
  "equal",
  "plus",
  "hypen",
  "asterisk",
  "dot",
  "numero",
  "menor",
  "mayor",
  "menorque",
  "mayorque",
  "diferente",
  "igualque",
  "and",
  "or",
  "not",
  "ollv",
  "cllv",
  "opar",
  "cpar",
  "hashtag",
  "ocorch",
  "ccorch",
  "comma",
  "identificador",
  "cadena",
  "echo",
  "if_",
  "else_",
  "repetir",
  "setcontenido",
  "setalineacion",
  "getpath",
  "beginHS",
  "getalineacion",
  "creartextoa",
  "creartextob",
  "crearimagen",
  "insertar",
  "clickboton",
  "getancho",
  "setpath",
  "setalto",
  "endHS",
  "setancho",
  "getalto",
  "creartabla",
  "setborde",
  "crearboton",
  "settexto",
  "gettexto"
  };
}

